### PR TITLE
Master

### PR DESCRIPTION
**Pull request by MarkH221**
Got perk combobox working, added a few more columns and tweaks to make future modifications a little easier.

### CODE REVIEW

**Comment by Kelnor277** [comment]
Thanks for the help. I really appreciate the help on the GUI.
I noticed you fixed the crash on cancel open save dialog too.
I kept forgetting to go back and handle that.

**Comment by Kelnor277** [comment]
Did you want to collaborate on this project? My GUI skills are weak, and I haven't had much time for the project ATM.

**Comment by MarkH221** [comment]
I wouldn't mind collaborating at all. Primarily I was interested in your use of derserialiser to parse the data, wasn't aware that could be made to work on the saves.

My own work caters exclusively to vanilla, specifically the console versions, key difference with them is compression algorithm used on the blocks, that and no checksums.

**Comment by Kelnor277** [comment]
I'm at work at the moment on my phone. I'm not using an out of the box
deserializer really. UE3 has its own serializer/deserializer and it uses it
to store game objects during save. It also seems firaxis might have
customized it. I was able to reverse engineer it using a hex editor and
some forum posts. It's a custom deserializer. It's been a while but I'll
look at my code when I get home. I tried to keep the deserializer module
project agnostic so you might be able to just grab the saverreader module
and inherit from the base classes for the specific stuff you want to
deserialize. Should probably move the lw roster specific classes to a new
namespace though. I'll go through and comment and document it tonight or at
the latest this weekend.

**Comment by Kelnor277** [comment]
Actually, looking closer at your commits. You seem to have a handle on it.
You can email me if you have questions.

There's a few spots in there that are long war specific like the fatigued
status.
I might work at migrating those out the savereader file so that the
savereader file just reads any Xcom save.

Two things I didn't do, because I don't need them for this are figuring out
how to recompress (CRC checks) and the difference in an Xbox Save vs PC
save.

**Comment by MarkH221** [comment]
My group has a toolkit for that, you can find it on referenced to on the wiki. Doesn't seem to handle long war very well as far as the checksum is concerned, still decompresses no problem however. The original author has long since lost the sourcecode and I'm aware of a few minor bugs in where it clips the header.

There's also the fact the endian is different, x86 is traditionally little endian while all the others are big, just means taking note of that when using bitconverter and such.

I was also thinking of doing that, I'm building a prototype to parse the soldier data based on this source code, I've already harvested as much of the vanilla enumerations as the wiki will provide, currently it doesn't work but I assume it's to do with endian.

**Comment by Kelnor277** [comment]
I have an idea to make the savereader.cs be reusable. I think all I have to
do is write a default deserializable class. Then have the structure case in
read property use the default class if there isn't a specific class for
that structure. The recursion should handle the rest. In theory it should
load the entire save file into memory because the save file is just nested
serialized objects. You could then write custom deserializers for specific
structures you want strongly typed. Would need a search function since you
may want specific objects that are nested inside like 20 layers of parents
that you don't care about but it would be a start.

**Pull request merged**
